ARG BASE=alpine:3.16

FROM ${BASE}

LABEL maintainer="Nischay Mamidi <NischayPro@protonmail.com>"

COPY entrypoint.sh /entrypoint.sh

COPY . /app

WORKDIR /app

RUN apk add --no-cache python3 py-pip git &&\
    pip3 install --upgrade gtts psycopg[binary] &&\
    pip3 install --upgrade python-telegram-bot &&\
    pip3 install git+https://github.com/Nischay-Pro/telegres

VOLUME [ "/app/config.json" ]

ENTRYPOINT [ "/entrypoint.sh" ]
