name: docker-build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    strategy:
      matrix:
        backend: [pickle, postgres]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            nischaypro/niscoin-{{ matrix.backend }}
            ghcr.io/Nischay-Pro/niscoin-{{ matrix.backend }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,suffix={{ matrix.backend }},pattern={{version}}
            type=semver,suffix={{ matrix.backend }},pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build pickle
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile.{{ matrix.backend }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}